### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by gsantner**
As discussed

### CODE REVIEW

**Comment by gsantner** [comment]
@Simpleyyt Pushed my changes

**Comment by gsantner** [comment]
ready for merge

**Comment by Simpleyyt** [comment]
Wrong style when deploy on github page. It seems that github don't support css template.

**Comment by gsantner** [comment]
of course it does. its just simple text replacement like any liquid-variable. I use it on all jekyll sites/gh-pages and it works^^.

**Comment by gsantner** [comment]
Ehm, you merged to master, but master is still with last commit from yesterday, is that a bug?

I need to find out why that happens espacially in your case, but for me everything works

**Pull request merged**
