### PR TITLE
Various improvements

### PR DESCRIPTION
**Pull request by gsantner**
Additionally to previous PR:
* Move css due to bug - frontmatter only parsed with main.*css as root

### CODE REVIEW

**Comment by gsantner** [comment]
You can test it out here: <https://openlauncherteam.github.io/>  / <https://github.com/OpenLauncherTeam/openlauncherteam.github.io>. It is exactly like in this PR. Only value that was changed was primary_color to red in _config.yml. and as you can see that works

**Comment by Simpleyyt** [comment]
Work fine.

**Comment by gsantner** [comment]
thanks. you may need to translate some words to your language. these are marked in the language files.

**Comment by Simpleyyt** [comment]
The translation is fine.

**Comment by gsantner** [comment]
yeah but it is in english, not in chinese (=not translated)

**Comment by Simpleyyt** [comment]
It's ok to mix Chinese and English. Some words look strange when translated to Chinese.

**Comment by gsantner** [comment]
Ah okay, didn't know that. Do you have something more planned or in work for the theme?

**Comment by Simpleyyt** [comment]
😭 To be honest, no.

**Comment by Simpleyyt** [comment]
Maybe I will develop some tools to make it easy to write post, just like: Prose.io.

**Comment by gsantner** [comment]
Okay so to be honest: I'm gonna use the theme on some project. These are the first 2 things I gonna do:
* Remove the title font (it increases load time, decreases readability). Gonna make it some standard font (like Verdana) that is available without loading some font additionally
* Change default language to EN

Would you mind getting this too into the this repo? I mean i can surely do it just in my project, but I think whynot make the base project better.

**Comment by gsantner** [comment]
I started something like that some days ago too: A application for editing and creating posts and pages in jekyll way. Based on Qt (Gui) C++ and a markdown editor.

**Comment by Simpleyyt** [comment]
😆 Haha, I think the font looks good.
I have already written one: <https://github.com/Simpleyyt/jekyll-editor>, but it don't work very well.

**Comment by gsantner** [comment]
okay, then not.

looked into your project too, but it is chrome + github. Would be great if it works for any jekyll site, e.g. stored offline a directory, or some git repo on some server. Thats the big problem currently: most editors are thought to be used on GitHub

**Comment by Simpleyyt** [comment]
Wow, great idea. It must be a big project.

**Comment by gsantner** [comment]
No it's not, currently it's file loading and showing markdown with syntax highlighting ;)

**Comment by Simpleyyt** [comment]
Maybe can share it to me when it is completed.

**Comment by gsantner** [comment]
I don't know if it will get ever finished :D.  
I am not used to Chrome plugin development, but maybe it would be a good idea to convert the project to some standalone app. E.g. using NodeJs, Electron etc. And to post it to some sites so others may improve it too

**Comment by Simpleyyt** [comment]
Yep, Google will remove support for Chrome apps. So I will migrate it to Electron.

**Comment by gsantner** [comment]
The theme doesn't work in subdirectories, some wrong references. I will need to send another PR...

**Pull request merged**
