### PR TITLE
Simple Jekyll Search ; fixes #17

### LINKED ISSUE #17: Suggestion for search
HI there, 
thanks for this great theme!  
I tried the search but it keeps redirecting to google search even if disabled in config.  
Maybe this search is worth a try, requires no external service: <https://github.com/christian-fei/Simple-Jekyll-Search/issues/74#issuecomment-302834800>

### PR DESCRIPTION
**Pull request by gsantner**
Makes use of <https://github.com/christian-fei/Simple-Jekyll-Search>.  
\- Search without external service. Done locally. Supports optionally fulltext search too.

### CODE REVIEW

**Comment by Simpleyyt** [comment]
Good job!

**Comment by gsantner** [comment]
thx, i got some more improvments. may i send another PR containing various/mixed improvements (some are e.g.. 1 line of change, some are file movements)? This gonna make the project a little easier to naviate on filesystem. 

E.g.

- moving tags, categories etc. in a single folder on FS, but still available at http:// .../tags/ (no difference in 
browsing)
- removing duoshuo `## duoshuo will be shutting down on June 1, 2017`

**Comment by gsantner** [comment]
and: should local search be default enabled? Would suit good as this works in all cases, with&without internet connection, without production-mode hosting and without domain :D

**Comment by Simpleyyt** [comment]
1. Yes, you can send another PR and I can see the improvements.
2. It can enable by default, just in the code of your PR.

**Pull request merged**
